name: carson-api

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ROOT_NAME: carson
  RESOURCE_GROUP: carson
  ACA_ENVIRONMENT: carson-app-environment

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        run: |
          echo "TAG=v$(TZ='America/Los_Angeles' date +%Y%m%d.%H%M%S)" >> "$GITHUB_ENV"
          echo "Using tag: ${TAG}"

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_ENDPOINT }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container
        run: |
          cd api
          docker build . -t ${{ secrets.REGISTRY_ENDPOINT }}/$ROOT_NAME-api:latest --build-arg GIT_VERSION_TAG=${TAG}
          docker push ${{ secrets.REGISTRY_ENDPOINT }}/$ROOT_NAME-api:latest

      - name: Push Container
        run: |
          az containerapp up --name $ROOT_NAME-api \
                              --image ${{ secrets.REGISTRY_ENDPOINT }}/$ROOT_NAME-api:latest \
                              --ingress external \
                              --target-port 8000 \
                              --resource-group $RESOURCE_GROUP \
                              --registry-server ${{ secrets.REGISTRY_ENDPOINT }} \
                              --registry-username ${{ secrets.REGISTRY_USERNAME }} \
                              --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
                              --environment $ACA_ENVIRONMENT

      - name: Logout
        run: |
          az logout
